### ISSUE TITLE
Linking error when building Debug version in Cygwin

### ISSUE THREAD

**Issue by inpefess** [vprover/vampire#519] opened 2024-01-14 14:29 UTC
I followed instruction from wiki https://github.com/vprover/vampire/wiki/Cygwin

`cmake ..` and then `make` builds with no errors.

But after `cmake .. -DCMAKE_BUILD_TYPE=Debug`, `make` fails with the following errors:

```
[100%] Linking CXX executable bin/vampire_z3_dbg_master_6994.exe
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/test_obj.dir/Test/TestUtils.cpp.o: in function `Test::Pretty<Kernel::Literal*>::prettyPrint(std::ostream&) const':
~/vampire/Test/TestUtils.cpp:105: multiple definition of `Test::Pretty<Kernel::Literal*>::prettyPrint(std::ostream&) const'; CMakeFiles/InterpretedFunctions_obj.dir/UnitTests/tInterpretedFunctions.cpp.o:~/vampire/Test/TestUtils.hpp:151: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/test_obj.dir/Test/TestUtils.cpp.o: in function `Test::Pretty<Kernel::Clause>::prettyPrint(std::ostream&) const':
~/vampire/Test/TestUtils.cpp:110: multiple definition of `Test::Pretty<Kernel::Clause>::prettyPrint(std::ostream&) const'; CMakeFiles/GaussianElimination_obj.dir/UnitTests/tGaussianElimination.cpp.o:~/vampire/Test/TestUtils.hpp:114: first defined here
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/test_obj.dir/Test/TestUtils.cpp.o: in function `Test::Pretty<Kernel::Literal>::prettyPrint(std::ostream&) const':
~/vampire/Test/TestUtils.cpp:125: multiple definition of `Test::Pretty<Kernel::Literal>::prettyPrint(std::ostream&) const'; CMakeFiles/InterpretedFunctions_obj.dir/UnitTests/tInterpretedFunctions.cpp.o:~/vampire/Test/TestUtils.hpp:114: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/vtest.dir/build.make:640: vtest.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:1913: CMakeFiles/vtest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target vampire
make: *** [Makefile:101: all] Error 2
```

**Comment by inpefess** [comment] 2024-01-21 11:04
So, to reproduce (on Cygwin):

```sh
git clone https://github.com/vprover/vampire
cd vampire
mkdir test_build
cd test_build
cmake .. -DCMAKE_BUILD_TYPE=Debug
make -j11 VERBOSE=1 > build.log 2>&1
```

[build.log](https://github.com/vprover/vampire/files/14000991/build.log)

**Comment by MichaelRawson** [comment] 2024-01-24 18:03
@joe-hauns - I'm not actually sure how this compiles normally. There's a template for `Pretty<T>`, specialised to various things, including `Pretty<Literal *>` (I think this one's redundant with respect to the existing `T *` specialisation), `Pretty<Literal>`, and `Pretty<Clause>`.

These last three are declared and defined in `TestUtils.cpp`, but are probably also used elsewhere (?). I think they probably want to get at least *declared* in the header file.

**Comment by joe-hauns** [comment] 2024-01-26 10:21
Yeah so the issue is definitely that the test code is being compiled into the main binary. 
I think i fixed this one issue (try compiling the branch `cygwin-test-fix`), but as compiling the tests into main is not expected there might be other issues coming up from time to time, e.g. if someone uses the same function names in multiple tests (e.g. `test01` or other informative names ;) ), so test functions should not be compiled into main after all.

**Comment by MichaelRawson** [comment] 2024-01-26 10:48
>Yeah so the issue is definitely that the test code is being compiled into the main binary.

Ah, sorry, I forgot to mention that - it *isn't*, just looks like it because of the multicore build output. Looking at the build log the failed command links  `vtest.exe`...but it sounds like you expect each test to be a separate binary?

**Comment by joe-hauns** [comment] 2024-01-29 10:08
Oh well no. Actually you're right then the tests are really one binary. I forgot that the `TEST_FUN` macro appends a prefix to every test function to prevent the error with `test01` i was hinting at. So everything sould be fine if we merge `cygwin-test-fix` (given this actually fixes the issue for that compiler).

**Comment by inpefess** [comment] 2024-02-01 19:20
I confirm that `cygwin-test-fix` builds under Cygwin and all the tests pass. @joe-hauns thank you!

**Comment by MichaelRawson** [comment] 2024-02-02 07:50
Merged directly, thanks @joe-hauns !

**Closed by MichaelRawson** 2024-02-02 07:50 UTC
