### ISSUE TITLE
An issue with fmb_adjust_sorts predicate

### ISSUE THREAD

**Issue by quickbeam123** [vprover/vampire#252] opened 2021-07-21 12:49 UTC
```
./vampire_dbg_master_5721 --saturation_algorithm fmb --fmb_adjust_sorts predicate Problems/SET/SET368-6.p
Running in auto input_syntax mode. Trying TPTP
Condition n < _size in file ./Lib/DArray.hpp, line 112 was violated, as:
n == 0
_size == 0
----- stack dump -----
Version : Vampire 4.5.1 (commit a7cbce58e on 2021-07-20 10:47:11 +0200)
Control points passed: 37153392
last control point:
        +DArray::operator[] const (37153392)
main
 vampireMode()
  doProving()
   ProvingHelper::runVampireSaturation
    ProvingHelper::runVampireSaturationImpl
     MainLoop::run
      FiniteModelBuilder::init
       DArray::operator[] const
----- end of stack dump -----
```
on TPTP 7.5.0

**Comment by selig** [comment] 2021-12-01 01:10
This PR should fix this issue

https://github.com/vprover/vampire/pull/305

I will be extending the PR with some other FMB fixes before it gets merged to Master.

The cause of the problem was how we track deleted function symbols, in particular, we default to assuming a function symbol has been deleted so a symbol introduced during the Sort Adjustment phase was being treated as deleted. This  adds to the evidence that we need to overhaul how we track the signature and deleted symbols.

**Closed** 2021-12-02 21:16 UTC
